spring.application.name=ms-docucloud
server.port=8080

# Perfil activo: usar "local" para desarrollo local (application-local.properties)
# Comentar o cambiar a "default" antes de hacer push
spring.profiles.active=default

#  AWS Credentials
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:}
spring.cloud.aws.credentials.session-token=${AWS_SESSION_TOKEN:}
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}

#  S3 
aws.s3.bucket=${AWS_S3_BUCKET:tallercloudnative}

#  EFS (path montado en el contenedor) 
efs.path=${EFS_PATH:/home/ec2-user/efs}

#  Multipart 
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#  Logs 
logging.level.software.amazon.awssdk=WARN
logging.level.io.awspring.cloud=WARN
logging.level.cl.duoc.ejemplo=DEBUG
